export ARCHS = armv6 arm64
export SDKVERSION = 8.4
export TARGET = iphone:clang
export TARGET_IPHONEOS_DEPLOYMENT_VERSION = 3.0
export ADDITIONAL_LDFLAGS = -Wl,-segalign,4000

include Makefile.common
